###
POST http://localhost:3000/api/v2/auth/register
Content-Type: application/json
x-api-key: superSeguro

{ 
    "username": "testy",
    "password": "test",
    "email": "juanangelbasgall@hotmail.com",
    "name": "test User"
}