@baseUrl = {{$dotenv API_BASE_URL}}
@apiKey = {{$dotenv SECRET_API_KEY}}
@legacyBaseUrl = {{$dotenv MU_SERVER_URL}}

GET {{baseUrl}}/health/readiness
Content-Type: application/json
x-api-key: {{apiKey}}

### old
GET {{legacyBaseUrl}}/health/readiness
Content-Type: application/json
x-api-key: {{apiKey}}

### old
GET {{legacyBaseUrl}}/api/status
Content-Type: application/json
x-api-key: {{apiKey}}