@baseUrl = {{$dotenv API_BASE_URL}}
@apiKey = {{$dotenv SECRET_API_KEY}}

GET {{baseUrl}}/launcher/servers
Content-Type: application/json
x-api-key: {{apiKey}}

### version
GET {{baseUrl}}/launcher?version=1.1.1
Content-Type: application/json
x-api-key: {{apiKey}}