@baseUrl = {{$dotenv API_BASE_URL}}
@apiKey = {{$dotenv SECRET_API_KEY}}
@legacyBaseUrl = {{$dotenv MU_SERVER_URL}}

GET {{baseUrl}}/ranking
Content-Type: application/json
x-api-key: {{apiKey}}

### v1
GET {{legacyBaseUrl}}/api/ranking
Content-Type: application/json
x-api-key: {{apiKey}}