@baseUrl = {{$dotenv API_BASE_URL}}
@apiKey = {{$dotenv SECRET_API_KEY}}

POST {{baseUrl}}/user
Content-Type: application/json
x-api-key: {{apiKey}}

{
  "username": "Juansito",
  "name": "John Doe",
  "email": "juanangelbasgall@hotmail.com"
}

### Get ALl
GET {{baseUrl}}/user
Content-Type: application/json
x-api-key: {{apiKey}}